export const incomeCategories: string[] = [
  "Allocation familiale",
  "Bonus",
  "Bourse d'études",
  "Dividendes",
  "Intérêts bancaires",
  "Pension",
  "Rente",
  "Revenus locatifs",
  "Revenus freelance",
  "Revenus partenariat",
  "Salaire",
  "Vente",
];

export const expenseCategories: string[] = [
  "Animaux de compagnie",
  "Assurances",
  "Cadeaux",
  "Courses Alimentaires",
  "Crédit Immobilier",
  "Crédit à la consommation",
  "Crédit auto",
  "Divertissement",
  "Eau et assainissement",
  "Entretien de la maison",
  "Epargne",
  "Gaz et chauffage",
  "Électricité",
  "Frais de scolarité",
  "Hypotèque",
  "Internet",
  "Investissement",
  "Loisir",
  "Loyer",
  "Restauration",
  "Soins médicaux",
  "Téléphone",
  "Transport",
  "Vêtements et accessoires",
];
