export const incomeCategories: string[] = [
  "Allocation Familiale",
  "Bonus",
  "Bourse d'Études",
  "Dividendes",
  "Intérêts Bancaires",
  "Pension",
  "Rente",
  "Revenus Locatifs",
  "Revenus Freelance",
  "Revenus Partenariat",
  "Salaire",
];

export const expenseCategories: string[] = [
  "Animaux de Compagnie",
  "Assurances",
  "Cadeaux",
  "Courses Alimentaires",
  "Crédit Immobilier",
  "Crédit à la Consommation",
  "Crédit auto",
  "Divertissement",
  "Eau et Assainissement",
  "Entretien de la Maison",
  "Factures de Gaz",
  "Factures d’Électricité",
  "Frais de Scolarité",
  "Hypotèque",
  "Internet",
  "Loisir",
  "Loyer",
  "Restauration",
  "Soins Médicaux",
  "Téléphone",
  "Transport",
  "Vêtements et Accessoires",
];
